version: '3.9'

services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb/pb_data

  frontend:
    build:
      context: ./frontend
      args:
        VITE_AUTHENTIK_URL: ${AUTHENTIK_URL}
        VITE_AUTHENTIK_APP_SLUG: ${AUTHENTIK_APP_SLUG}
        VITE_AUTHENTIK_CLIENT_ID: ${AUTHENTIK_CLIENT_ID}
        VITE_KIOSK_SECRET: ${KIOSK_SECRET:-}
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - backend

volumes:
  pocketbase_data:
